<a href="https://colab.research.google.com/github/VisithraRavichandran/HALIFA/blob/SDLC/NavieBayesClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving pacific.csv to pacific.csv

In [ ]:
data=pd.read_csv('pacific.csv')
data

,ID,Name,Date,Time,Event,Status,Latitude,Longitude,Maximum Wind,Minimum Pressure,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,EP011949,UNNAMED,19490611,0,,TS,20.2N,106.3W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,EP011949,UNNAMED,19490611,600,,TS,20.2N,106.4W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,EP011949,UNNAMED,19490611,1200,,TS,20.2N,106.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,EP011949,UNNAMED,19490611,1800,,TS,20.3N,107.7W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,EP011949,UNNAMED,19490612,0,,TS,20.4N,108.6W,45,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26132,EP222015,SANDRA,20151128,1200,,LO,21.7N,109.0W,35,1002,...,0,0,0,0,0,0,0,0,0,0
26133,EP222015,SANDRA,20151128,1800,,LO,22.4N,108.7W,30,1007,...,0,0,0,0,0,0,0,0,0,0
26134,EP222015,SANDRA,20151129,0,,LO,23.1N,108.3W,30,1008,...,0,0,0,0,0,0,0,0,0,0
26135,EP222015,SANDRA,20151129,600,,LO,23.5N,107.9W,25,1009,...,0,0,0,0,0,0,0,0,0,0
26136,EP222015,SANDRA,20151129,1200,,LO,24.2N,107.7W,20,1010,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
pre_columns=data[:]
pre_columns.drop(['ID','Name','Date','Status','Time','Event','Latitude','Longitude'],axis=1,inplace=True)
pre_columns

/tmp/ipykernel_1797/2388353499.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pre_columns.drop(['ID','Name','Date','Status','Time','Event','Latitude','Longitude'],axis=1,inplace=True)

,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,45,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26132,35,1002,60,0,0,0,0,0,0,0,0,0,0,0
26133,30,1007,0,0,0,0,0,0,0,0,0,0,0,0
26134,30,1008,0,0,0,0,0,0,0,0,0,0,0,0
26135,25,1009,0,0,0,0,0,0,0,0,0,0,0,0
26136,20,1010,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
relevant_cols=pre_columns.columns
relevant_cols

Index(['Status', 'Maximum Wind', 'Minimum Pressure', 'Low Wind NE',
       'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE',
       'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW',
       'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW'],
      dtype='object')

In [ ]:
train,test=train_test_split(data,test_size=0.2)
train_X=train[relevant_cols]
train_Y=train['Status']
test_X=test[relevant_cols]
test_Y=test['Status']

In [ ]:
#Use Model
gnb=GaussianNB()

In [ ]:
pd.DataFrame({'Actual':test_Y,'Predicted':predicated_gnb})

      Actual Predicted
10088     TS        ET
25587     LO        DB
6683      HU        DB
18399     TD        ET
9016      TD        ET
...      ...       ...
2036      TS        ET
23431     TD        ET
6225      TS        ET
12185     TD        ET
2654      TS        DB

[5228 rows x 2 columns]